apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  # namespace: namespace-calculator:1.0.0-17
  labels:
    app: calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: raemondarellano/calculator:1.0.0-17
        ports:
        - containerPort: 80
