apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-calculator:1.0.0-9
  # namespace: namespace-calculator:1.0.0-9
  labels:
    app: app-calculator:1.0.0-9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-calculator:1.0.0-9
  template:
    metadata:
      labels:
        app: app-calculator:1.0.0-9
    spec:
      containers:
      - name: c-calculator:1.0.0-9
        image: raemondarellano/calculator:1.0.0-9
        ports:
        - containerPort: 80
