apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-calculator
  labels:
    app: calculator-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: c-calculator
        image: raemondarellano/my-calculator:1.0.0-50
        ports:
        - containerPort: 80 
