apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-calculator:1.0.0-7
  namespace: namespace-calculator:1.0.0-7
  labels:
    app: app-calculator:1.0.0-7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-calculator:1.0.0-7
  template:
    metadata:
      labels:
        app: app-calculator:1.0.0-7
    spec:
      containers:
      - name: c-calculator:1.0.0-7
        image: raemondarellano/calculator:1.0.0-7
        ports:
        - containerPort: 80
