apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-calculator:1.0.0-8
  # namespace: namespace-calculator:1.0.0-8
  labels:
    app: app-calculator:1.0.0-8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-calculator:1.0.0-8
  template:
    metadata:
      labels:
        app: app-calculator:1.0.0-8
    spec:
      containers:
      - name: c-calculator:1.0.0-8
        image: raemondarellano/calculator:1.0.0-8
        ports:
        - containerPort: 80
