apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  # namespace: namespace-calculator:1.0.0-9
  labels:
    app: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-container
        image: raemondarellano/calculator:1.0.0-9
        ports:
        - containerPort: 80
