apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator:1.0.0-10
  # namespace: namespace-calculator:1.0.0-10
  labels:
    app: calculator:1.0.0-10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator:1.0.0-10
  template:
    metadata:
      labels:
        app: calculator:1.0.0-10
    spec:
      containers:
      - name: calculator:1.0.0-10
        image: raemondarellano/calculator:1.0.0-10
        ports:
        - containerPort: 80
